### ISSUE TITLE
Missing <span.h>

### ISSUE THREAD

**Issue by JPGygax68** [matus-chochlik/oglplu2#2]
Hi! I'd very much like to start using your library, which looks well-designed and professionally executed. Not to mention incredibly thorough!

However I'm stuck right at the beginning because the file `span.h` seems to be missing. `span.hpp` tries to include that at line 25.

Another problem that I had I was able to workaround: though CMake had detected GLFW3, it then complained that GLFW was not available. I copied the lib and include paths of GLFW3 into those of GLFW, which allowed configure to run to completion.

**Comment by matus-chochlik** [comment]
Hi, thanks for Your kind words,

Concerning `span.h` You need to:
`git submodule init`
`cd third_party/GSL`
`git submodule update`

I'll have a look at the GLFW issue.

HTH

**Comment by JPGygax68** [comment]
Thanks. I had completely forgotten to check for submodules.

I'm getting metric tons of compilation errors though, most of them probably due to MSVC 2015 problems. I'm going to open separate issues for those I can't handle.

**Comment by matus-chochlik** [comment]
Yeah, ATM the only compiler known to work is clang++ 3.6
